yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),

]
handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/about/models.py
# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from pytils.translit import slugify

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(null=False, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse("group_posts", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)[:100]
        super().save(*args, **kwargs)


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(Group,
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts'
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    ) 

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        if not self:
            self = slugify(self.text)[:15]
        super().save(*args, **kwargs)

yatube/users/models.py
# Create your models here.

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        labels = {'group': 'Группа', 'text': 'Текст поста'}
        help_texts = {'group': 'Группа, к которой будет относиться пост',
                      'text': 'Текст нового поста'}
        fields = ['text', 'group', 'image']

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView
# Create your views here.


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render

def page_not_found(request, exception):
    # Переменная exception содержит отладочную информацию; 
    # выводить её в шаблон пользовательской страницы 404 мы не станем
    return render(request, 'core/404.html', {'path': request.path}, status=404)

def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from .models import Post, Group, User

from .utils import get_page_context

SHORT_TEXT = 30
POSTS_NUMBER = 10


def index(request):
    posts = Post.objects.all()
    page_obj = get_page_context(request, posts, POSTS_NUMBER)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = get_page_context(request, group.posts.all(), POSTS_NUMBER)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    author_total_posts = Post.objects.filter(author_id=author.pk).count()
    page_obj = get_page_context(request, author.posts.all(), POSTS_NUMBER)
    context = {
        'author': author,
        'author_total_posts': author_total_posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author_total_posts = Post.objects.filter(author_id=post.author.pk).count()
    post1 = post.text
    context = {
        'post': post,
        'author_total_posts': author_total_posts,
        'post1': post1
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect(reverse('posts:profile',
                            kwargs={'username': request.user}))


@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if post.author != request.user:
        return redirect(reverse('posts:profile',
                                kwargs={'username': request.user}))
    if form.is_valid():
        post = form.save()
        return redirect(reverse('posts:post_detail',
                        kwargs={'post_id': post_id}))
    
    return render(request, 'posts/create_post.html',
                  {'form': form, 'is_edit': is_edit, 'post': post})

yatube/users/views.py
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Меня зовут Настя. И я только учусь программировать. Это мой первый (более-менее) серьезный проект. 
  Но мне нравится программировать...иногда.)))А иногда мне хочется просто выкинуть компьютер из окна, потому-что ничего не получается)))
  Но каждый раз справляясь со сложной задачей я радуюсь и понимаю что все возможно.
  И это классно!
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>  
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
    {% include 'includes/header.html'%}
    </header>
    <main>
      <div class="container">
        <h1>{% block header %}{% endblock %}</h1>
        {% block content %}
        <!-- Содержимое страницы -->
        {% endblock %} 
    </div>
  </main>
    {% include 'includes/footer.html'%}
  </body>    
    </html>
 

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %} 

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© {{year}} Copyright 
    <p><span style="color:red">Ya</span>tube</p>
</footer>
  

yatube/templates/includes/header.html
{% load static %}
      <nav class="navbar navbar-light" style="background-color: lightskyblue"> 
        <div class="container"> 
          <a class="navbar-brand" href="{% url 'posts:index' %}"> 
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> 
            <span style="color:red">Ya</span>tube 
          </a>
      <ul class="nav nav-pills">
  {% with request.resolver_match.view_name as view_name %}  
  <li class="nav-item">              
    <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
      href="{% url 'about:author' %}"
    >
      Об авторе
    </a>
  </li>
  {% endwith %} 
  {% with request.resolver_match.view_name as view_name %}  
  <li class="nav-item">              
    <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
       href="{% url 'about:tech' %}"
    >
    Технологии
    </a>
  </li>
  {% endwith %} 
{%  if user.is_authenticated  %}
  {% with request.resolver_match.view_name as view_name %}  
  <li class="nav-item">              
    <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
       href="{% url 'posts:post_create' %}"
    >
    Новая запись
    </a>
  </li>
  {% endwith %} 
    <li class="nav-item"> 
      <a class="nav-link link-light" href="<!--  -->">Изменить пароль</a>
        </li>
  {% with request.resolver_match.view_name as view_name %}  
  <li class="nav-item">              
    <a class="nav-link {% if view_name  == 'users:logout' %}active{% endif %}" 
       href="{% url 'users:logout' %}"
    >
    Выйти
    </a>
  </li>
  {% endwith %} 
    <li>
      Пользователь: {{ user.username }}
    </li>
{% else %}
  {% with request.resolver_match.view_name as view_name %}  
  <li class="nav-item">              
    <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" 
      href="{% url 'users:login' %}"
    >
    Войти
    </a>
  </li>
       {% endwith %} 
       {% with request.resolver_match.view_name as view_name %}  
       <li class="nav-item">              
         <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" 
           href="{% url 'users:signup' %}"
         >
         Регистрация
         </a>
       </li>
        {% endwith %} 
        {% endif %}
      </ul>
    </div>
  </nav>      
</header> > 

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}

  {% block title %}
    {% if is_edit %}
      Редактировать запись
    {% else %}
      Добавить запись
    {% endif %}
  {% endblock %}

  {% block header %}
    {% if is_edit %}
      Редактировать запись
    {% else %}
      Добавить запись
    {% endif %}
  {% endblock %}
  
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактирование поста
        {% else %}
          Новый пост
        {% endif %}
      </div>
      <div class="card-body">
        {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            {{ field.label }}: {{ error|escape }}
          {% endfor %}
        {% endfor %}
        {% endif %}
      <div class="card-body">
        <form method="post"  enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif %}" >
          {% csrf_token %} 
          {% for field in form %}
            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
              <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
            </div>
            </div>
                {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}               
              </button>
            </div>
          </form>
        </div> 
      </div> 
    </div> 
  </div> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block header %}
  Записи сообщества {{ group }}
{% endblock %} 
{% block title %}
  Записи сообщества {{ group }}
{% endblock %}
{% block content %}
{% load thumbnail %}
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </article> 
      <br>
      {% if post.group %}     
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы </a>
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}    
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block header %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
{% load thumbnail %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
      <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  </article> 
    <br>  
  {% if post.group %}   
    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы </a>
{% endif %} 
{% if not forloop.last %}<hr>{% endif %} 
{% endfor %}
{% include 'includes/paginator.html' %} 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block header %}
 {{ group }}
{% endblock %} 
{% block content %}
{% load thumbnail %}
{% block title %}
{{ title }}
{% endblock %}

      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации:  {{ post.pub_date|date:"d E Y" }} 
            </li>
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}">
              {% endif %}
                все записи группы
              </a>
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ author_total_posts }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
          <p>
            {{ post.text }} 
          </p>
           <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>  
        </article>
      </div> 
    {% endblock %}
  

yatube/templates/posts/profile.html
  {% extends "base.html" %}
    {% block title %} Профайл пользователя {{ author.get_full_name }}
    {% endblock %} 
  {% block header %}
    Все посты пользователя {{ author.get_full_name }} 
  {% endblock %}
  {% block content %}
  {% load thumbnail %}
  {% for post in page_obj %}   
      <h3>Всего постов: {{ author_total_posts }}</h3>    
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article> 
        {% if post.group %}      
          <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        {% endif %}        > 
        {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}  
  {% endblock %}
  

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block content %}
{% block title %}Вы вышли из системы{% endblock %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'posts:index' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 